document.write( '<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\n' );
document.write( '  <div class=\"container-fluid\">\n' );
document.write( '    <!--ICON & 標題-->\n' );
document.write( '    <a class=\"navbar-brand\" href=\"#\">\n' );
document.write( '      <img src=\"https://i.imgur.com/73cBzrL.png\" alt=\"\" width=\"24\" height=\"24\" class=\"d-inline-block align-text-top\">\n' );
document.write( '      Yuto\'s Note\n' );
document.write( '    </a><!--ICON & 標題結束-->\n' );
document.write( '    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n' );
document.write( '      <span class=\"navbar-toggler-icon\"></span>\n' );
document.write( '    </button>\n' );
document.write( '    <!--其他頁面-->\n' );
document.write( '    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n' );
document.write( '      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\n' );
document.write( '        <li class=\"nav-item\">\n' );
document.write( '          <a class=\"nav-link active\" aria-current=\"page\" href=\"index.html\">首頁</a>\n' );
document.write( '        </li>\n' );
document.write( '        <li class=\"nav-item\">\n' );
document.write( '          <a class=\"nav-link\" href=\"content.html\">文章</a>\n' );
document.write( '        </li>\n' );
document.write( '        <li class=\"nav-item dropdown\">\n' );
document.write( '          <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n' );
document.write( '            作品集\n' );
document.write( '          </a>\n' );
document.write( '          <ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n' );
document.write( '            <li><a class=\"dropdown-item\" href=\"note.html\">Js備忘錄</a></li>\n' );
document.write( '          </ul>\n' );
document.write( '        </li><!--下拉選單結束-->\n' );
document.write( '        <!--下拉選單-->\n' );
document.write( '        <li class=\"nav-item dropdown\">\n' );
document.write( '          <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n' );
document.write( '            更多\n' );
document.write( '          </a>\n' );
document.write( '          <ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n' );
document.write( '            <li><a class=\"dropdown-item\" href=\"login.html\">登入</a></li>\n' );
document.write( '            <li><a class=\"dropdown-item\" href=\"download.html\">下載</a></li>\n' );
document.write( '          </ul>\n' );
document.write( '        </li><!--下拉選單結束-->\n' );
document.write( '      </ul>\n' );
document.write( '    </div><!-- 其他頁面結束 -->\n' );
document.write( '  </div>\n' );
document.write( '</nav>\n' );